// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: weather.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const weatherCreate = `-- name: WeatherCreate :one
INSERT INTO weather (
	id,
	observed_at,
	temperature_actual,
	temperature_apparent,
	precipitation_total,
	precipitation_rain,
	precipitation_snowfall,
	wind_speed,
	wind_gusts,
	wind_direction,
	condition_code,
	condition_description,
	cloud_cover,
	humidity
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) RETURNING id, created_at, updated_at, observed_at, temperature_actual, temperature_apparent, precipitation_total, precipitation_rain, precipitation_snowfall, wind_speed, wind_gusts, wind_direction, condition_code, condition_description, cloud_cover, humidity
`

type WeatherCreateParams struct {
	ID                    uuid.UUID `db:"id" json:"id"`
	ObservedAt            time.Time `db:"observed_at" json:"observed_at"`
	TemperatureActual     float64   `db:"temperature_actual" json:"temperature_actual"`
	TemperatureApparent   float64   `db:"temperature_apparent" json:"temperature_apparent"`
	PrecipitationTotal    float64   `db:"precipitation_total" json:"precipitation_total"`
	PrecipitationRain     float64   `db:"precipitation_rain" json:"precipitation_rain"`
	PrecipitationSnowfall float64   `db:"precipitation_snowfall" json:"precipitation_snowfall"`
	WindSpeed             float64   `db:"wind_speed" json:"wind_speed"`
	WindGusts             float64   `db:"wind_gusts" json:"wind_gusts"`
	WindDirection         int64     `db:"wind_direction" json:"wind_direction"`
	ConditionCode         int64     `db:"condition_code" json:"condition_code"`
	ConditionDescription  string    `db:"condition_description" json:"condition_description"`
	CloudCover            int64     `db:"cloud_cover" json:"cloud_cover"`
	Humidity              int64     `db:"humidity" json:"humidity"`
}

func (q *Queries) WeatherCreate(ctx context.Context, arg WeatherCreateParams) (Weather, error) {
	row := q.db.QueryRowContext(ctx, weatherCreate,
		arg.ID,
		arg.ObservedAt,
		arg.TemperatureActual,
		arg.TemperatureApparent,
		arg.PrecipitationTotal,
		arg.PrecipitationRain,
		arg.PrecipitationSnowfall,
		arg.WindSpeed,
		arg.WindGusts,
		arg.WindDirection,
		arg.ConditionCode,
		arg.ConditionDescription,
		arg.CloudCover,
		arg.Humidity,
	)
	var i Weather
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.TemperatureActual,
		&i.TemperatureApparent,
		&i.PrecipitationTotal,
		&i.PrecipitationRain,
		&i.PrecipitationSnowfall,
		&i.WindSpeed,
		&i.WindGusts,
		&i.WindDirection,
		&i.ConditionCode,
		&i.ConditionDescription,
		&i.CloudCover,
		&i.Humidity,
	)
	return i, err
}

const weatherFind = `-- name: WeatherFind :one
SELECT id, created_at, updated_at, observed_at, temperature_actual, temperature_apparent, precipitation_total, precipitation_rain, precipitation_snowfall, wind_speed, wind_gusts, wind_direction, condition_code, condition_description, cloud_cover, humidity FROM weather WHERE id = ?
`

func (q *Queries) WeatherFind(ctx context.Context, id uuid.UUID) (Weather, error) {
	row := q.db.QueryRowContext(ctx, weatherFind, id)
	var i Weather
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.TemperatureActual,
		&i.TemperatureApparent,
		&i.PrecipitationTotal,
		&i.PrecipitationRain,
		&i.PrecipitationSnowfall,
		&i.WindSpeed,
		&i.WindGusts,
		&i.WindDirection,
		&i.ConditionCode,
		&i.ConditionDescription,
		&i.CloudCover,
		&i.Humidity,
	)
	return i, err
}
